title: Picolog1012-acquisition-card-app
description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/titimar16/Picolog1012-Acquisition-Card-App/archive/master.zip
  tar_url: https://github.com/titimar16/Picolog1012-Acquisition-Card-App/tarball/master
gems:
  - jekyll-mentions
